import csv
import re






# hospitals_processed = open('hospitals_processed.csv', 'w')

# with open('hospital.csv', 'r') as csvfile:

# 	dataRows = csv.reader(csvfile, delimiter=',')
# 	for idx, line in enumerate(dataRows):
# 		outString = ""
# 		if idx == 0:
# 			for i in range(len(line)):
# 				outString += line[i] + ","
# 			outString += "latitude,longitude"
# 			outString += "\n"
# 			hospitals_processed.write(outString)
# 		else:
# 			r = re.findall(r'\d+.\d+, \-\d+.\d+', line[28])
# 			if r:
# 				coord = r[0].split(",")
# 				latitude = str(float(coord[0]))
# 				longitude = str(float(coord[1]))

# 				for i in range(len(line)):
# 					outString += "\"" + line[i] + "\"" + ","
				
# 				outString += latitude + ',' + longitude
# 				outString += "\n"
# 				hospitals_processed.write(outString)







states = [
	"AL",
	"AK",
	"AZ",
	"AR",
	"CA",
	"CO",
	"CT",
	"DE",
	"FL",
	"GA",
	"HI",
	"ID",
	"IL",
	"IN",
	"IA",
	"KS",
	"KY",
	"LA",
	"ME",
	"MD",
	"MA",
	"MI",
	"MN",
	"MS",
	"MO",
	"MT",
	"NE",
	"NV",
	"NH",
	"NJ",
	"NM",
	"NY",
	"NC",
	"ND",
	"OH",
	"OK",
	"OR",
	"PA",
	"RI",
	"SC",
	"SD",
	"TN",
	"TX",
	"UT",
	"VT",
	"VA",
	"WA",
	"WV",
	"WI",
	"WY",
	"DC"
]

surgeries = [
	"003 - ECMO OR TRACH W MV >96 HRS OR PDX EXC FACE, MOUTH & NECK W MAJ O.R.",
	"004 - TRACH W MV 96+ HRS OR PDX EXC FACE, MOUTH & NECK W/O MAJ O.R.",
	"027 - CRANIOTOMY & ENDOVASCULAR INTRACRANIAL PROCEDURES W/O CC/MCC",
	"039 - EXTRACRANIAL PROCEDURES W/O CC/MCC",
	"057 - DEGENERATIVE NERVOUS SYSTEM DISORDERS W/O MCC",
	"066 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W/O CC/MCC",
	"069 - TRANSIENT ISCHEMIA",
	"074 - CRANIAL & PERIPHERAL NERVE DISORDERS W/O MCC",
	"087 - TRAUMATIC STUPOR & COMA, COMA <1 HR W/O CC/MCC",
	"093 - OTHER DISORDERS OF NERVOUS SYSTEM W/O CC/MCC",
	"101 - SEIZURES W/O MCC",
	"103 - HEADACHES W/O MCC",
	"149 - DYSEQUILIBRIUM",
	"153 - OTITIS MEDIA & URI W/O MCC",
	"165 - MAJOR CHEST PROCEDURES W/O CC/MCC",
	"176 - PULMONARY EMBOLISM W/O MCC",
	"179 - RESPIRATORY INFECTIONS & INFLAMMATIONS W/O CC/MCC",
	"189 - PULMONARY EDEMA & RESPIRATORY FAILURE",
	"192 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W/O CC/MCC",
	"195 - SIMPLE PNEUMONIA & PLEURISY W/O CC/MCC",
	"203 - BRONCHITIS & ASTHMA W/O CC/MCC",
	"204 - RESPIRATORY SIGNS & SYMPTOMS",
	"206 - OTHER RESPIRATORY SYSTEM DIAGNOSES W/O MCC",
	"207 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT 96+ HOURS",
	"208 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT <96 HOURS",
	"221 - CARDIAC VALVE & OTH MAJ CARDIOTHORACIC PROC W/O CARD CATH W/O CC/MCC",
	"227 - CARDIAC DEFIBRILLATOR IMPLANT W/O CARDIAC CATH W/O MCC",
	"234 - CORONARY BYPASS W CARDIAC CATH W/O MCC",
	"236 - CORONARY BYPASS W/O CARDIAC CATH W/O MCC",
	"238 - MAJOR CARDIOVASC PROCEDURES W/O MCC",
	"244 - PERMANENT CARDIAC PACEMAKER IMPLANT W/O CC/MCC",
	"247 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W/O MCC",
	"249 - PERC CARDIOVASC PROC W NON-DRUG-ELUTING STENT W/O MCC",
	"251 - PERC CARDIOVASC PROC W/O CORONARY ARTERY STENT W/O MCC",
	"254 - OTHER VASCULAR PROCEDURES W/O CC/MCC",
	"264 - OTHER CIRCULATORY SYSTEM O.R. PROCEDURES",
	"267 - ENDOVASCULAR CARDIAC VALVE REPLACEMENT W/O MCC",
	"282 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W/O CC/MCC",
	"287 - CIRCULATORY DISORDERS EXCEPT AMI, W CARD CATH W/O MCC",
	"293 - HEART FAILURE & SHOCK W/O CC/MCC",
	"301 - PERIPHERAL VASCULAR DISORDERS W/O CC/MCC",
	"303 - ATHEROSCLEROSIS W/O MCC",
	"305 - HYPERTENSION W/O MCC",
	"310 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W/O CC/MCC",
	"312 - SYNCOPE & COLLAPSE",
	"313 - CHEST PAIN",
	"328 - STOMACH, ESOPHAGEAL & DUODENAL PROC W/O CC/MCC",
	"331 - MAJOR SMALL & LARGE BOWEL PROCEDURES W/O CC/MCC",
	"355 - HERNIA PROCEDURES EXCEPT INGUINAL & FEMORAL W/O CC/MCC",
	"373 - MAJOR GASTROINTESTINAL DISORDERS & PERITONEAL INFECTIONS W/O CC/MCC",
	"379 - G.I. HEMORRHAGE W/O CC/MCC",
	"390 - G.I. OBSTRUCTION W/O CC/MCC",
	"392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISORDERS W/O MCC",
	"395 - OTHER DIGESTIVE SYSTEM DIAGNOSES W/O CC/MCC",
	"419 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W/O CC/MCC",
	"440 - DISORDERS OF PANCREAS EXCEPT MALIGNANCY W/O CC/MCC",
	"446 - DISORDERS OF THE BILIARY TRACT W/O CC/MCC",
	"455 - COMBINED ANTERIOR/POSTERIOR SPINAL FUSION W/O CC/MCC",
	"460 - SPINAL FUSION EXCEPT CERVICAL W/O MCC",
	"462 - BILATERAL OR MULTIPLE MAJOR JOINT PROCS OF LOWER EXTREMITY W/O MCC",
	"468 - REVISION OF HIP OR KNEE REPLACEMENT W/O CC/MCC",
	"470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC",
	"473 - CERVICAL SPINAL FUSION W/O CC/MCC",
	"482 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W/O CC/MCC",
	"483 - MAJOR JOINT/LIMB REATTACHMENT PROCEDURE OF UPPER EXTREMITIES",
	"494 - LOWER EXTREM & HUMER PROC EXCEPT HIP,FOOT,FEMUR W/O CC/MCC",
	"517 - OTHER MUSCULOSKELET SYS & CONN TISS O.R. PROC W/O CC/MCC",
	"520 - BACK & NECK PROC EXC SPINAL FUSION W/O CC/MCC",
	"536 - FRACTURES OF HIP & PELVIS W/O MCC",
	"552 - MEDICAL BACK PROBLEMS W/O MCC",
	"554 - BONE DISEASES & ARTHROPATHIES W/O MCC",
	"556 - SIGNS & SYMPTOMS OF MUSCULOSKELETAL SYSTEM & CONN TISSUE W/O MCC",
	"558 - TENDONITIS, MYOSITIS & BURSITIS W/O MCC",
	"563 - FX, SPRN, STRN & DISL EXCEPT FEMUR, HIP, PELVIS & THIGH W/O MCC",
	"603 - CELLULITIS W/O MCC",
	"605 - TRAUMA TO THE SKIN, SUBCUT TISS & BREAST W/O MCC",
	"621 - O.R. PROCEDURES FOR OBESITY W/O CC/MCC",
	"639 - DIABETES W/O CC/MCC",
	"641 - MISC DISORDERS OF NUTRITION,METABOLISM,FLUIDS/ELECTROLYTES W/O MCC",
	"652 - KIDNEY TRANSPLANT",
	"658 - KIDNEY & URETER PROCEDURES FOR NEOPLASM W/O CC/MCC",
	"684 - RENAL FAILURE W/O CC/MCC",
	"690 - KIDNEY & URINARY TRACT INFECTIONS W/O MCC",
	"694 - URINARY STONES W/O ESW LITHOTRIPSY W/O MCC",
	"696 - KIDNEY & URINARY TRACT SIGNS & SYMPTOMS W/O MCC",
	"708 - MAJOR MALE PELVIC PROCEDURES W/O CC/MCC",
	"743 - UTERINE & ADNEXA PROC FOR NON-MALIGNANCY W/O CC/MCC",
	"812 - RED BLOOD CELL DISORDERS W/O MCC",
	"813 - COAGULATION DISORDERS",
	"863 - POSTOPERATIVE & POST-TRAUMATIC INFECTIONS W/O MCC",
	"864 - FEVER",
	"870 - SEPTICEMIA OR SEVERE SEPSIS W MV >96 HOURS",
	"872 - SEPTICEMIA OR SEVERE SEPSIS W/O MV >96 HOURS W/O MCC",
	"881 - DEPRESSIVE NEUROSES",
	"884 - ORGANIC DISTURBANCES & MENTAL RETARDATION",
	"885 - PSYCHOSES",
	"894 - ALCOHOL/DRUG ABUSE OR DEPENDENCE, LEFT AMA",
	"897 - ALCOHOL/DRUG ABUSE OR DEPENDENCE W/O REHABILITATION THERAPY W/O MCC",
	"918 - POISONING & TOXIC EFFECTS OF DRUGS W/O MCC",
	"948 - SIGNS & SYMPTOMS W/O MCC"
]

myDict = {}

surgery_state_averages = open('surgery_state_averages.csv', 'w')

for state in states:
	for surgery in surgeries:
		myDict[state + " " + surgery] = []
			
with open('medicare.csv', 'r') as csvfile:

	dataRows = csv.reader(csvfile, delimiter=',')
	for idx, line in enumerate(dataRows):
		if idx != 0:
			if line[5] + " " + line[0] in myDict:
				myDict[line[5] + " " + line[0]].append(float(line[10]))

	for key in myDict:
		if len(myDict[key]) != 0:
			average = sum(myDict[key])/len(myDict[key])
			myDict[key] = average
		else:
			myDict[key] = 0
			#myDict.pop(key, None)

	surgery_state_averages.write("Surgery,State,Cost\n")

	for key in myDict:
		outString = ""
		outString = ""
		keyString = key.partition(" ")
		state = keyString[0]
		surgery = keyString[2]
		print state
		print surgery
		surgery_state_averages.write("\"" + surgery + "\"," + state + "," + str(myDict[key]) + "\n")

		

			
